<?php

function pdonline_questions_menu()
{
	$items = array();
	//Replicates logging ins
	$items['identity'] = array
	(
		'title' => 'PDOnline',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('identity_form'),
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_NORMAL_ITEM
	);

	//Contains all the questions to answer
	$items['questions'] = array
	(
		'title' => 'Questions - Please click "PDOnline" under the navigation to generate another question.',
		'description' => 'Answer all the questions',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('questions_form'),
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	//Contains the report along with import/export feature
	$items['report'] = array
	(
		'title' => 'Result - Please click "PDOnline" under the navigation to generate another question.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('questions_report'),
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);
	return $items;
}

function identity_form()
{
	$form = array();
	$form['id'] = array
	(
		'#type' => 'textfield',
		'#title' => 'User ID '
	);

	$form['firstName'] = array
	(
		'#type' => 'textfield',
		'#title' => 'First Name'
	);

	$form['lastName'] = array
	(
		'#type' => 'textfield',
		'#title' => 'Last Name '
	);

	$form['submit'] = array
	(
		'#type' => 'submit',
		'#value' => 'Submit'
	);

	$form['#submit'][]='identity_form_submit';

	return $form;
}

function identity_form_submit($form, &$form_state)
{
	/*Stores values in these variable to later be used when generating the questions.
		The reason for randomizing in this function is to prevent any re-randomizing whenever
		the question_form's "submit" is pressed
	*/  
	$id = $form_state['values']['id'];
	$firstName = $form_state['values']['firstName'];
	$lastName = $form_state['values']['lastName'];
	$oneN = rand(1,100);
	$twoN = rand(1,10);
	$threeN = rand(1,100);
	$fourN = rand(1,5);
	$fourC = chr(rand(97,122));
	$fiveN = rand(1,5);
	getOneYX($oneX, $oneY);

	//Inserts the user's info into the database
	$con = mysqli_connect("localhost","lloyd4567","pdonline4567","questions");
	if(mysqli_connect_errno())
	{
		drupal_set_message("Failed to connect " . mysqli_connect_error);
	}
	$sql = mysqli_query($con, "INSERT INTO QuestionUsers(id,firstName,lastName)
						VALUES ('$id','$firstName','$lastName')");

	$options = array
	(
		'query' => array
		(
			'oneN' => $oneN,
			'oneX' => $oneX,
			'oneY' => $oneY,
			'twoN' => $twoN,
			'threeN' => $threeN,
			'fourN' => $fourN,
			'fourC' => $fourC,
			'fiveN' => $fiveN,
			'id' => $id,
		)
	);
	mysqli_close($con);
	
	//Redirects to the questions page along with the parameters
	$form_state['redirect'] = array('questions', $options);
}

function questions_form($form, &$form_state)
{
	//Obtains the values from the URL
	$oneN = $_GET['oneN'];
	$oneX = $_GET['oneX'];
	$oneY = $_GET['oneY'];
	$twoN = $_GET['twoN'];
	$threeN = $_GET['threeN'];
	$fourN = $_GET['fourN'];
	$fourC = $_GET['fourC'];
	$fiveN = $_GET['fiveN'];
	$id = $_GET['id'];

	$form = array();
	$form['divisible'] = array
	(
		'#type' => 'textfield',
		'#title' => '1) Is '.$oneN.' divisble by '.$oneX.' , '.$oneY.' , both or neither? <br/>
				<ul>			
					<li>If '.$oneX.' : Input "P"</li>
					<li>If '.$oneY.' : Input "D"</li>
					<li>If both: Input "PDOnline"</li>
					<li>If neither: Input '. $oneN .'</li>
				</ul>'
	);
	$form['oneN'] = array('#type' => 'hidden', '#value' => $oneN);
	$form['oneX'] = array('#type' => 'hidden', '#value' => $oneX);
	$form['oneY'] = array('#type' => 'hidden', '#value' => $oneY);

	$form['factorial'] = array
	(
		'#type' => 'textfield',
		'#title' => '2) What is '.$twoN.' factorial? '
	);
	$form['twoN'] = array('#type' => 'hidden', '#value' => $twoN);

	$form['bits'] = array
	(
		'#type' => 'textfield',
		'#title' => '3) How many bits are set in the binary conversion of '.$threeN
	);
	$form['threeN'] = array('#type' => 'hidden', '#value' => $threeN);

	$form['words'] = array
	(
		'#type' => 'textfield',
		'#title' => '4) Write '.$fourN.' words containing the character "'.$fourC.'"'
	);
	$form['fourN'] = array('#type' => 'hidden', '#value' => $fourN);
	$form['fourC'] = array('#type' => 'hidden', '#value' => $fourC);

	$form['html'] = array
	(
		'#type' => 'textarea',
		'#title' => '5) Write some HTML with the word "PDOnline" nested '.$fiveN.' levels deep '
	);
	$form['fiveN'] = array('#type' => 'hidden', '#value' => $fiveN);

	$form['id'] = array('#type' => 'hidden', '#value' => $id);

	$form['submit'] = array
	(
		'#type' => 'submit',
		'#value' => 'Submit'
	);

	$form['#submit'][]='questions_form_submit';

	return $form;
}

function questions_form_validate($form, &$form_state)
{
	if($form_state['values']['divisible'] == "")
	{
		form_set_error('divisible', 'Q1 is empty');
	}

	if($form_state['values']['factorial'] == "")
	{
		form_set_error('factorial', 'Q2 is empty');
	}

	if(!is_numeric($form_state['values']['factorial']))
	{
		form_set_error('factorial', 'Q2 answer can only be numeric');
	}

	if($form_state['values']['bits'] == "")
	{
		form_set_error('bits', 'Q3 is empty');
	}

	if(!is_numeric($form_state['values']['bits']))
	{
		form_set_error('bits', 'Q3 answer can only be numeric');
	}

	if($form_state['values']['words'] == "")
	{
		form_set_error('words', 'Q4 is empty');
	}

	$words = explode(" ", $form_state['values']['words']);
	if(count($words) != $form_state['values']['fourN'])
	{
		form_set_error('words', $form_state['values']['fourN'].' words needed for Q3. You input '. count($words));
	}

	if($form_state['values']['html'] == "")
	{
		form_set_error('html', 'Q5 is empty');
	}
}


function questions_form_submit($form, &$form_state)
{
		$oneResult = checkDivisible($form_state['values']['oneN'], $form_state['values']['oneX'], $form_state['values']['oneY'], $form_state['values']['divisible']);
		$twoResult = checkFactorial($form_state['values']['twoN'], $form_state['values']['factorial']);
		$threeResult = checkBits($form_state['values']['threeN'], $form_state['values']['bits']);
		$fourResult = checkWords($form_state['values']['fourC'], $form_state['values']['words']);
		$fiveResult = checkHtml($form_state['values']['fiveN'], $form_state['values']['html']);
		getScores($oneResult, $twoResult, $threeResult, $fourResult, $fiveResult, $totalScore, $percentageScore);
		$id = $form_state['values']['id'];

		$con = mysqli_connect("localhost","lloyd4567","pdonline4567","questions");
		if(mysqli_connect_errno())
		{
			drupal_set_message("Failed to connect " . mysqli_connect_error);
		}
		//Performs a delete SQL to make sure one account only has one result
		mysqli_query($con, "DELETE Results FROM Results,QuestionUsers
							WHERE Results.userID = '$id'");

		//Inserts values into the Results table
		$sql = mysqli_query($con, "INSERT INTO Results(id,questionOne,questionTwo,questionThree,questionFour,questionFive,totalScore,percentageScore,userID)
							VALUES (0,'$oneResult','$twoResult','$threeResult','$fourResult','$fiveResult','$totalScore','$percentageScore','$id')");
		mysqli_close($con);

		$options = array
		(
			'query' => array
			(
				'id' => $id,
			)
		);
		$form_state['redirect'] = array('report', $options); 							
}


function questions_report()
{
	$id = $_GET['id'];
	$form = array();	
	$con = mysqli_connect("localhost","lloyd4567","pdonline4567","questions");
	if(mysqli_connect_errno())
	{
		drupal_set_message("Failed to connect " . mysqli_connect_error);
	}
	//Obtains the User's result and displays it to the user
	$results = mysqli_query($con, "SELECT *
    								FROM QuestionUsers, Results
    								WHERE Results.userID = '$id';");
	while($row = mysqli_fetch_array($results))
	{
		$form['html'] = array
		(
			'#markup' =>
		"<h1>Please click 'PDOnline' under the navigation to generate a set of question again</h1><br /><br /><hr />".
		"Name: " . $row['firstName'] . " " . $row['lastName'] . "<hr/>".
		"<table style='width:500px'>".
			"<th align='left'>Question</th>".
			"<th align='left'>Result</th>".
			"<tr>".
				"<td>1</td>".
				"<td>".$row['questionOne']."</td>".
			"</tr>".
			"<tr>".
				"<td>2</td>".
				"<td>".$row['questionTwo']."</td>".
			"</tr>".
			"<tr>".
				"<td>3</td>".
				"<td>".$row['questionThree']."</td>".
			"</tr>".
			"<tr>".
				"<td>4</td>".
				"<td>".$row['questionFour']."</td>".
			"</tr>".
			"<tr>".
				"<td>5</td>".
				"<td>".$row['questionFive']."</td>".
			"</tr>".
		"</table>".
		"<hr/> Total Score: " . $row['totalScore'] . "/5<br />".
		"Percentage Score: " . $row['percentageScore'] . " %<br /><hr />"
		);

		$form['contents'] = array
		(
			'#type' => 'hidden', 
			'#value' => $row['firstName']." ".$row['lastName'].
					" - Q1 ".$row['questionOne'].
					" - Q2 ".$row['questionTwo'].
					" - Q3 ".$row['questionThree'].
					" - Q4 ".$row['questionFour'].
					" - Q5 ".$row['questionFive'].
					" - Total Score ".$row['totalScore'].
					" - Percentage Score ".$row['percentageScore']
					
	);
	}
	mysqli_close($con);

	//Asks for the fileName to import/export to.
	$form['textFile'] = array
	(
		'#type' => 'textfield',
		'#title' => 'Enter fileName '
	);

	$form['actions']['submit'] = array
	(
		'#type' => 'submit',
		'#value' => 'import'
	);

	$form['actions']['submit2'] = array
	(
		'#type' => 'submit',
		'#value' => 'export',
		'#submit' => array('questions_report_export')
	);
	return $form;
}

function questions_report_validate($form, &$form_state)
{
	if($form_state['values']['textFile'] == "")
	{
		form_set_error('textFile', 'Please enter a file name');
	}
}

//Writes to the file
function questions_report_submit($form, &$form_state)
{
	
	$file = fopen($_SERVER['DOCUMENT_ROOT']."/".$form_state['values']['textFile'].'.txt',"w");
	fwrite($file, $form_state['values']['contents']);
	fclose($file);
	drupal_set_message("Saved");
	drupal_set_message("<hr />Please click 'PDOnline' under the navigation to generate a set of question again");
}

//Reads the file
function questions_report_export($form, &$form_state)
{
	$i = 0;
	$file = fopen($_SERVER['DOCUMENT_ROOT']."/".$form_state['values']['textFile'].'.txt',"r");
	$contents = fread($file, filesize($_SERVER['DOCUMENT_ROOT']."/".$form_state['values']['textFile'].'.txt'));
	$tags = explode(" - ", $contents);
	foreach($tags as $tag)
	{
		drupal_set_message($tag);
	}
	drupal_set_message("<hr />Please click 'PDOnline' under the navigation to generate a set of question again");
	fclose($file);
}

//Makes sure Y and X are not the same
function getOneYX(&$oneX, &$oneY)
{
	do
	{
		$oneX = rand(2,5);
		$oneY = rand(2,5);
	}while($oneX === $oneY);
}

/*Functions below checks if the
	user's answers are correct
*/
function checkDivisible($oneN, $oneX, $oneY, $userAns)
{
	$result = 'Incorrect';
	if($oneN % $oneX == 0 && $oneN % $oneY == 0)
	{
		$ans = "PDOnline";
	}
	else if($oneN % $oneX == 0)
	{
		$ans = 'P';
	}
	else if($oneN % $oneY == 0)
	{
		$ans = 'D';
	}
	else
	{
		$ans = $oneN;
	}

	if($userAns == $ans)
	{
		$result = 'Correct';
	}
	return $result;
}

function checkFactorial($twoN, $userAns)
{
	$ans = 1;
	$result = "Incorrect";	
	for($i = 1; $i <= $twoN; $i++)
	{
		$ans = $ans * $i;
	}
	if($userAns == $ans)
	{
		$result = 'Correct';
	}
	return $result;
}

function checkBits($threeN, $userAns)
{
	$bitsEquivalent = decbin($threeN); //Converts decimal to binary
	$ans = strlen($bitsEquivalent); //obtains the length of the string
	$result = "Incorrect";
	if($userAns == $ans)
	{
		$result = 'Correct';
	}
	return $result;
}

function checkWords($fourC, $userAns)
{
	$result = "Correct";
	$words = explode(" ", $userAns); //Splits the words
	foreach($words as $word)
	{
		//Checks if each word contains the character
		if(strpos($word, $fourC) === false)
		{
			$result = "Incorrect";
		}
	}
	return $result;
}

/*The way it checks is that it strips all html tags
	and checks if PDOnline is actually written.
	The initial plan was to split each tag but
	I cannot think of a way to do it
*/
function checkHtml($fiveN, $userAns)
{
	$result = "Incorrect";
	$combinedString = preg_replace("/\s+/","", $userAns);
	$word = strip_tags($combinedString);
	if($word == 'PDOnline')
	{
		$result = "Correct";
	}
	return $result;
}

/*Obtains the score of the user*/
function getScores($oneResult, $twoResult, $threeResult, $fourResult, $fiveResult, &$totalScore, &$percentageScore)
{
	$totalScore = 0;
	if($oneResult == 'Correct')
		$totalScore++;
	if($twoResult == 'Correct')
		$totalScore++;
	if($threeResult == 'Correct')
		$totalScore++;
	if($fourResult == 'Correct')
		$totalScore++;
	if($fiveResult == 'Correct')
		$totalScore++;
	$percentageScore = round(($totalScore/5) * 100);
}

