<?php

function pdonline_questions_menu()
{
	$items = array();
	$items['questions'] = array
	(
		'title' => 'Questions',
		'description' => 'Answer all the questions',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('questions_form'),
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);

	$items['report'] = array
	(
		//'title' => 'Questions',
		//'description' => 'Answer all the questions',
		'page callback' => 'questions_report',
		//'page arguments' => array('questions_form'),
		'access callback' => 'user_access',
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK
	);
	return $items;
}

function questions_form()
{
	$oneN = rand(1,100);
	$twoN = rand(1,10);
	$threeN = rand(1,100);
	$fourN = rand(1,5);
	$fourC = chr(rand(97,122));
	$fiveN = rand(1,5);
	getOneYX($oneX, $oneY);
	$form = array();
	$form['divisible'] = array
	(
		'#type' => 'textfield',
		'#title' => '1) Is '.$oneN.' divisble by '.$oneX.' , '.$oneY.' , both or neither? <br/>
				<ul>			
					<li>If '.$oneX.' : Input "P"</li>
					<li>If '.$oneY.' : Input "D"</li>
					<li>If both: Input "PDOnline"</li>
					<li>If neither: Input '. $oneN .'</li>
				</ul>'
	);
	$form['oneN'] = array('#type' => 'hidden', '#value' => $oneN);
	$form['oneX'] = array('#type' => 'hidden', '#value' => $oneX);
	$form['oneY'] = array('#type' => 'hidden', '#value' => $oneY);

	$form['factorial'] = array
	(
		'#type' => 'textfield',
		'#title' => '2) What is '.$twoN.' factorial? '
	);
	$form['twoN'] = array('#type' => 'hidden', '#value' => $twoN);

	$form['bits'] = array
	(
		'#type' => 'textfield',
		'#title' => '3) How many bits are set in the binary conversion of '.$threeN
	);
	$form['threeN'] = array('#type' => 'hidden', '#value' => $threeN);

	$form['words'] = array
	(
		'#type' => 'textfield',
		'#title' => '4) Write '.$fourN.' words containing the character "'.$fourC.'"'
	);
	$form['fourN'] = array('#type' => 'hidden', '#value' => $fourN);
	$form['fourC'] = array('#type' => 'hidden', '#value' => 'l');

	$form['html'] = array
	(
		'#type' => 'textarea',
		'#title' => '5) Write some HTML with the word "PDOnline" nested '.$fiveN.' levels deep '
	);
	$form['fiveN'] = array('#type' => 'hidden', '#value' => $fiveN);


	$form['submit'] = array
	(
		'#type' => 'submit',
		'#value' => 'Submit'
	);

	$form['#submit'][]='questions_form_submit';

	return $form;
}

function questions_form_validate($form, &$form_state)
{
	if($form_state['values']['divisible'] == "")
	{
		form_set_error('divisible', 'Q1 is empty');
	}

	if($form_state['values']['factorial'] == "")
	{
		form_set_error('factorial', 'Q2 is empty');
	}

	if(!is_numeric($form_state['values']['factorial']))
	{
		form_set_error('factorial', 'Q2 answer can only be numeric');
	}

	if($form_state['values']['bits'] == "")
	{
		form_set_error('bits', 'Q3 is empty');
	}

	if(!is_numeric($form_state['values']['bits']))
	{
		form_set_error('bits', 'Q3 answer can only be numeric');
	}


	if($form_state['values']['words'] == "")
	{
		form_set_error('words', 'Q4 is empty');
	}

	if($form_state['values']['html'] == "")
	{
		form_set_error('html', 'Q5 is empty');
	}
}


function questions_form_submit($form, &$form_state)
{
		//$form_state['redirect'] = 'report';
		$oneResult = checkDivisible($form_state['values']['oneN'], $form_state['values']['oneX'], $form_state['values']['oneY'], $form_state['values']['divisible']);
		drupal_set_message("1) " . $oneResult);
		$twoResult = checkFactorial($form_state['values']['twoN'], $form_state['values']['factorial']);
		drupal_set_message("2) " . $twoResult);
		$threeResult = checkBits($form_state['values']['threeN'], $form_state['values']['bits']);
		drupal_set_message("3) " . $threeResult);
		$fourResult = checkWords($form_state['values']['fourC'], $form_state['values']['words']);
		drupal_set_message("4) " . $fourResult);
		$fiveResult = checkHtml($form_state['values']['fiveN'], $form_state['values']['html']);
		drupal_set_message("4) " . $fiveResult);

		$con = mysqli_connect("localhost","lloyd4567","pdonline4567","questions");
		if(mysqli_connect_errno())
		{
			drupal_set_message("Failed to connect " . mysqli_connect_error);
		}
		$sql = mysqli_query($con, "INSERT INTO Results(id,questionOne,questionTwo,questionThree,questionFour,questionFive,totalScore,percentageScore)
							VALUES (0,'Correct','Correct','Correct','Correct','Correct',5,100)");
		if(!mysqli_query($con,$sql))
		{
			die('Error: '. mysqli_error($con));
		}
		mysqli_close($con); 							
}

function questions_report()
{
	echo "Hello";
}

function getOneYX(&$oneX, &$oneY)
{
	do
	{
		$oneX = rand(2,5);
		$oneY = rand(2,5);
	}while($oneX === $oneY);
}

function checkDivisible($oneN, $oneX, $oneY, $userAns)
{
	$result = 'Incorrect';
	if($oneN % $oneX == 0 && $oneN % $oneY == 0)
	{
		$ans = "PDOnline";
	}
	else if($oneN % $oneX == 0)
	{
		$ans = 'P';
	}
	else if($oneN % $oneX == 0)
	{
		$ans = 'D';
	}
	else
	{
		$ans = $oneN;
	}

	if($userAns == $ans)
	{
		$result = 'Correct';
	}
	return $result;
}

function checkFactorial($twoN, $userAns)
{
	$ans = 1;
	$result = "Incorrect";	
	for($i = 1; $i <= $twoN; $i++)
	{
		$ans = $ans * $i;
	}
	if($userAns == $ans)
	{
		$result = 'Correct';
	}
	return $result;
}

function checkBits($threeN, $userAns)
{
	$bitsEquivalent = decbin($threeN);
	$ans = strlen($bitsEquivalent);
	$result = "Incorrect";
	if($userAns == $ans)
	{
		$result = 'Correct';
	}
	return $result;
}

function checkWords($fourC, $userAns)
{
	$result = "Correct";
	$words = explode(" ", $userAns);
	foreach($words as $word)
	{
		if(strpos($word, $fourC) === false)
		{
			$result = "Incorrect";
		}
	}
	return $result;
}

function checkHtml($fiveN, $userAns)
{
	$result = "Incorrect";
	$combinedString = preg_replace("/\s+/","", $userAns);
	$word = strip_tags($combinedString);
	if($word == 'PDOnline')
	{
		$result = "Correct";
	}
	return $result;
}

